name: "Docker build"

on:
  push:
    branches:
      - github-registry

jobs:
  buildx:
    name: "Docker build and push"
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --tag ghcr.io/eastata/yet-another-one-github-search:latest \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            --file ./Dockerfile ./
